# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - misspell
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - revive

linters-settings:
  gofmt:
    simplify: true
  
  govet:
    enable-all: true
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  unparam:
    check-exported: false
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  revive:
    severity: warning
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    
    # Exclude known issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Exclude shadow checking on err variables
    - text: "shadow: declaration of .err."
      linters:
        - govet
  
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
  print-linter-name: true
