services:
  ven-api:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - ssh_key
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-ven-redis-pass}
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - FROM_EMAIL=noreply@techyouth.com
      - FROM_NAME=TechYouth
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-admin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-password123}
      - MINIO_USE_SSL=false
    volumes:
      - ./uploads:/root/uploads
      - ./app.db:/root/app.db
    depends_on:
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started
      minio:
        condition: service_healthy
    networks:
      - ven-network

  redis:
    image: redis:7-alpine
    container_name: ven_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-ven-redis-pass}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - ven-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ven-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web interface
    networks:
      - ven-network

  minio:
    image: minio/minio:latest
    container_name: ven-minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password123}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ven-network
networks:
    ven-network:
      driver: bridge

volumes:
  redis_data:
    driver: local
  minio_data:
    driver: local

secrets:
  ssh_key:
    file: ~/.ssh/id_ed25519