services:
  ven-api:
    build: .
    container_name: ven-api
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-ven-redis-pass}
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    volumes:
      - ./uploads:/root/uploads
      - ./app.db:/root/app.db
    depends_on:
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - ven-network

  redis:
    image: redis:7-alpine
    container_name: ven_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-ven-redis-pass}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - ven-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ven-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web interface
    networks:
      - ven-network
networks:
    ven-network:
      driver: bridge

volumes:
  redis_data:
    driver: local