definitions:
  dto.CompleteLessonRequest:
    properties:
      lesson_id:
        type: string
      score:
        type: integer
      time_spent:
        type: integer
    required:
    - lesson_id
    - score
    - time_spent
    type: object
  dto.CreateSessionRequest:
    properties:
      device_id:
        type: string
    required:
    - device_id
    type: object
  dto.LessonAccessResponse:
    properties:
      can_access:
        type: boolean
      reason:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.LoginResponse:
    properties:
      access_token:
        type: string
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.RegisterResponse:
    properties:
      user_id:
        type: string
    type: object
  shared.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/guest/progress/{sessionId}:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves the progress of a guest session
      parameters:
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Guest Progress
      tags:
      - guest
  /api/v1/guest/progress/{sessionId}/add-hearts:
    post:
      consumes:
      - application/json
      description: This endpoint adds hearts to a guest session when an ad is watched
      parameters:
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Add Hearts from Ad
      tags:
      - guest
  /api/v1/guest/progress/{sessionId}/complete:
    post:
      consumes:
      - application/json
      description: This endpoint marks a lesson as completed for a guest session
      parameters:
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      - description: Complete lesson request
        in: body
        name: completeLessonRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CompleteLessonRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Complete Lesson
      tags:
      - guest
  /api/v1/guest/progress/{sessionId}/lesson/{lessonId}/access:
    get:
      consumes:
      - application/json
      description: This endpoint checks if a guest session can access a specific lesson
      parameters:
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      - description: Lesson ID
        in: path
        name: lessonId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.LessonAccessResponse'
              type: object
      summary: Check Lesson Access
      tags:
      - guest
  /api/v1/guest/progress/{sessionId}/lose-heart:
    post:
      consumes:
      - application/json
      description: This endpoint deducts a heart from a guest session when a lesson
        is failed
      parameters:
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Lose Heart
      tags:
      - guest
  /api/v1/guest/session:
    post:
      consumes:
      - application/json
      description: This endpoint creates a new guest session or retrieves an existing
        one based on device ID
      parameters:
      - description: Create session request
        in: body
        name: createSessionRequest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateSessionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create or Get Guest Session
      tags:
      - guest
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: This endpoint logs in a user
      parameters:
      - description: Login request
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.LoginResponse'
              type: object
      summary: Login
      tags:
      - auth
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: This endpoint registers a user
      parameters:
      - description: Register request
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RegisterResponse'
              type: object
      summary: Register
      tags:
      - auth
  /ping:
    get:
      consumes:
      - application/json
      description: This endpoint checks the health of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/shared.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Ping
      tags:
      - health
swagger: "2.0"
